ema:
  _target_: mode.callbacks.ema.EMA
  decay: 0.999
  start_step: 0
  save_ema_weights_in_callback_state: True
  evaluate_ema_weights_instead: True

  power: 0.6666666666666666
  inv_gamma: 1.0
  min_value: 0.0
  max_value: 0.9999

# Temporarily disabled rollout_lh callback due to robosuite dependency issue
# rollout_lh:
#   _target_: mode.rollout.libero_rollout.RolloutLibero
#   _recursive_: false
#   env_cfg:
#     _target_: mode.wrappers.hulc_wrapper.HulcWrapper
#   skip_epochs: ${rollout_lh_skip_epochs}
#   benchmark_name: ${libero_benchmark}
#   rollout_freq: 10
#   num_videos: 0
#   num_sequences: 50 # 128
#   max_steps: 520
#   empty_cache: false
#   debug: false
#   n_eval: 20
#   num_procs: 10
#   use_mp: false
#   task_embedding_format: clip
#   device: ${device}


checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_top_k: 3
  verbose: True
  monitor: val_act/lang_act_loss_pp  # Changed from eval_lh/avg_seq_len since rollout_lh callback is disabled
  mode: min  # Changed from max since we want to minimize loss
  dirpath: saved_models
  filename: '{epoch:02d}_{val_act/lang_act_loss_pp:.4f}'  # Updated filename to match new monitor metric
  every_n_epochs: 1  # Changed from ${callbacks.rollout_lh.rollout_freq} since rollout_lh is disabled